routes/web.php
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::get('/', function () {
	return view('welcome');
});
Route::get('/sample', 'Attendance\AttendanceController@viewAttendance')->name('sample');

Auth::routes();

// Route::post("register-user", "Auth\RegisterUserController@store")->name("register-user");
//Acadmic Year Route
Route::get('/home', 'HomeController@index')->name('acadmic-year');
Route::get('/myprofile', 'Profile\ProfileController@index')->name("myprofile");
// Acadmic year management
Route::get('/manage-year', 'HomeController@manageyear')->name("manage-year");
Route::POST('/update-year', 'HomeController@store')->name("update-year");
Route::POST('/addYear', 'HomeController@addYear');
Route::POST('/editYear', 'HomeController@editYear')->name("editYear");
Route::POST('/deleteYear', 'HomeController@deleteYear');

//Route::group(['middleware' => ['web']], function () {
Route::resource('/post', 'PostController');
Route::POST('/addPost', 'PostController@addPost');
Route::POST('/editPost', 'PostController@editPost');
Route::POST('/deletePost', 'PostController@deletePost');
//});

//Faculty Management Route
Route::resource('/faculty-view', 'Faculty\FacultyController@index');
Route::get('/faculty-view', 'Faculty\FacultyController@index')->name('faculty-view');
Route::post('/faculty-add', 'Faculty\FacultyController@store')->name('faculty-add');

//routes for Ajax faculty managements
Route::POST('/editFaculty', 'Faculty\FacultyController@editFaculty');
Route::POST('/deleteFaculty', 'Faculty\FacultyController@deleteFaculty');

//Class Adviser Routes
Route::get('/faculty-class', 'Faculty\ClassAdviserController@index')->name('faculty-class');
Route::post('/store-class-ca', 'Faculty\ClassAdviserController@store')->name('store-class-ca');
Route::post('/editClassAdviser', 'Faculty\ClassAdviserController@editClassAdviser')->name('edit-class');

// subjects routes:
Route::resource('/subjects-view', 'Subject\SubjectController@index');
Route::get('/subjects-view', 'Subject\SubjectController@index')->name('subjects-view');
Route::POST('/subjects-view', 'Subject\SubjectController@index')->name('subjects-view');
Route::POST('/subjects-store', 'Subject\SubjectController@store')->name('subjects-store');
Route::POST('/subjectsEdit', 'Subject\SubjectController@subjectsEdit')->name('subjectsEdit');
Route::POST('/subjectsDelete', 'Subject\SubjectController@subjectsDelete')->name('subjectsDelete');

//subject teachers routes
Route::get('/subject-teachers', 'Subject\SubjectTeacherController@index')->name('subject-teachers');
Route::POST('/subject-teachers-store', 'Subject\SubjectTeacherController@store')->name('subject-teachers-store');
Route::POST('/deletePost', 'PostController@deletePost');

//program outcomes routes

Route::get('/program-outcomes', 'PoController@index')->name('program-outcomes');

Route::get('/po', 'PoController\PoController@index')->name('po');
Route::get('/pso', 'PoController\PoController@create')->name('pso');

/**
 * Route grouping for subjects
 *
 **/
Route::group(["prefix" => "subjects"], function () {

	Route::get("/", "Subject\SubjectController@index")->name("subjects.list");

	Route::post("/", "Subject\SubjectController@store")->name("subjects.store");

	Route::delete("/delete-school", "Subject\SubjectController@destroy")->name("subjects.destroy");
});

// Course file routes
Route::group(["prefix" => "course-file"], function () {
	Route::get('/', 'CourseFile\CourseFileController@index')->name('course-file');
	Route::get('/my-subjects', 'CourseFile\MySubjectsController@index')->name('my-subjects');
	Route::get('/view-subject', 'CourseFile\MySubjectsController@view')->name('view-my-subject');
	Route::get('/edit-subject', 'CourseFile\MySubjectsController@editSubject')->name('edit-my-subject');
	Route::get('co-statements', 'CourseFile\CoController@coindex')->name('co-statements');
	Route::post('deleteCO', 'CourseFile\CoController@deleteCO')->name('deleteCO');
	Route::post('co-add', 'CourseFile\CoController@store')->name('co-add');
	Route::get('co-po-mappings', 'CoPoMappings\CoPoMappingController@copoindex')->name('co-po-mappings');
	Route::post('/store-mappings', 'CoPoMappings\CoPoMappingController@store')->name('store-mappings');
	Route::get('internals', 'Internals\TestController@index')->name('internals');
	Route::get('internals/upload-marks', 'Internals\TestController@uploadMarks')->name('test-upload-marks');
	Route::post('internals/store-subject-marks', 'Internals\TestController@storeMarks')->name('store-subject-marks');
	Route::get('internals/test-attainment', 'Internals\TestController@testAttainment')->name('test-attainment');

});

Route::group(["prefix" => "attendance"], function () {
	Route::get('/', 'Attendance\AttendanceController@index')->name('attendance');
	Route::get('take-attendance', 'Attendance\AttendanceController@takeAttendance')->name('take-attendance');
	Route::get('extra-attendance', 'Attendance\AttendanceController@extraAttendance')->name('extra-attendance');
	Route::post('select-elective', 'Attendance\AttendanceController@selectElective')->name('select-elective');
	Route::get('store-extra-attendance', 'Attendance\AttendanceController@storeExtraAttendance')->name('store-extra-attendance');
	Route::post('save-attendance', 'Attendance\AttendanceController@saveAttendance')->name('save-attendance');
	Route::get('view-attendance', 'Attendance\AttendanceController@viewAttendance')->name('view-attendance');
	Route::get('view-subject-attendance', 'Attendance\AttendanceController@viewSubjectAttendance')->name('view-subject-attendance');
	Route::get('defaulter-list', 'Attendance\AttendanceController@defaulterList')->name('defaulter-list');
	Route::get('view-defaulter-list', 'Attendance\AttendanceController@viewDefaulter')->name('view-defaulter-list');
	Route::get('generate-defaulter', 'Attendance\AttendanceController@generateDefaulter')->name('generate-defaulter');
	Route::get('take-practical-attendance', 'Attendance\PracticalAttendanceController@takeAttendance')->name('take-practical-attendance');
	Route::get('view-practical-attendance', 'Attendance\PracticalAttendanceController@takeAttendance')->name('view-practical-attendance');
	Route::post('save-practical-attendance', 'Attendance\PracticalAttendanceController@saveAttendance')->name('save-practical-attendance');
	Route::get('view-practical-defaulter-list', 'Attendance\PracticalAttendanceController@viewDefaulter')->name('view-practical-defaulter-list');
	Route::get('view-final-defaulter-list', 'Attendance\FinalAttendanceController@finalDefaulter')->name('view-final-defaulter-list');

});
//co po mappings routes

//Unit Test Management
Route::group(["prefix" => "test-management"], function () {
	Route::get('/', 'UnitTest\UnitTestController@index')->name('test-management');
	Route::get('/question-bank', 'UnitTest\UnitTestController@questionBank')->name('question-bank');
	Route::get('/subject-question-bank', 'UnitTest\QuestionBankController@viewQuestions')->name('subject-question-bank');
	Route::get('/add-questions', 'UnitTest\QuestionBankController@index')->name('add-questions');
	Route::get('/edit-question', 'UnitTest\QuestionBankController@editQuestion')->name('edit-question');
	Route::post('store-questions', 'UnitTest\QuestionBankController@store')->name('store-questions');
	Route::post('deleteQuestion', 'UnitTest\QuestionBankController@deleteQuestion')->name('deleteQuestion');
	Route::post("store-img-question", "UnitTest\QuestionBankController@storeImageQuestion")->name("store-img-question");
	Route::post('/importQuestions', 'UnitTest\QuestionBankController@importQuestions')->name('importQuestions');
	Route::post('select-co', 'UnitTest\QuestionBankController@selectCo')->name('select-co');
	Route::get('question-paper', 'UnitTest\QuestionPaperController@index')->name('question-paper');
	Route::post('store-question-paper', 'UnitTest\QuestionPaperController@store')->name('store-question-paper');
	Route::get('view-test-paper', "UnitTest\QuestionPaperController@viewTestPaper")->name('view-test-paper');
	Route::get('create-pdf', "UnitTest\QuestionPaperController@createPDF")->name('create-pdf');

	// Route::group(["prefix" => "question-banks"], function () {
	Route::post("ajax-question-banks", "UnitTest\QuestionBankController@showQuestions")->name("question-banks-index");
	// });
	//Route::post('/question-bank', 'UnitTest\UnitTestController@questionBank')->name('question-bank');
	//Route::post('/question-bank/add-questions', 'UnitTest\UnitTestController@questionAdd')->name('add-questions');
	//Route::post('/deleteCO', 'CourseFile\CoController@deleteCO')->name('deleteCO');
	//Route::post('/co-add', 'CourseFile\CoController@store')->name('co-add');

});

// Route::post('student-management/search', 'Students\StudentController@search')->name('student-management.search');

Route::group(["prefix" => "student-management"], function () {
	Route::get("/", 'Students\StudentController@index')->name("student-management");
	Route::get("add-students", 'Students\StudentController@addStudents')->name("add-students");
	Route::post("store-students", "Students\StudentController@store")->name("store-students");
	Route::post("select-elective-subject", "Students\StudentController@electiveSubject")->name("select-elective-subject");
	Route::post("edit-student", 'Students\StudentController@test')->name("edit-student");
	Route::post('update-student', 'Students\StudentController@updateStudent')->name("update-student");
	Route::resource('student-management', 'Students\StudentController');
	Route::POST('deleteStudent', 'Students\StudentController@deleteStudent');
	Route::POST('importStudents', 'Students\StudentController@importStudents')->name('importStudents');
	//Route::get('edit-student', 'Students\StudentController@edit')->name("edit-student");

app/models/Student.php
<?php

namespace App\models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Student extends Model {

	use SoftDeletes, Sluggable;

	public function sluggable() {
		return [
			'slug' => [
				'source' => 'student_name',
			],
		];
	}

	public function attendences() {
		return $this->hasMany(Attendance::class, "student_id", "id");
	}
}

resources/views/students/add.blade.php
@extends('layouts.admin_layout')
@section('content')
<section class="content">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header">
          <h2>Add New Students</h2>
            </div>
              <div class="body">
                   @if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif
    @if (Session::has('error'))
          <div class="alert alert-danger">
        {{ session('success') }}
    </div>
    @endif
                <div class="panel panel-info">
                  <div class="panel-heading" role="tab" id="headingOne_1">
                    <h4 class="panel-title">
                      <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion_1" href="#collapseOne_1" aria-expanded="false" aria-controls="collapseOne_1"> Import Excel File
                      </a>
                    </h4>
                    </div>
                    <div id="collapseOne_1" class="panel-collapse collapse in" role="tabpanel"aria-labelledby="headingOne_1">
                      <div class="panel-body">
                         <form method="post" action="{{ route('importStudents') }}" enctype="multipart/form-data">
                             {{ csrf_field() }}
                          <div class="row clearfix">
                            <div class="col-sm-4">
                              <input type="hidden" name="acadmic_year_id" value="{{$acyear->id}}">
                             <select class="form-control" name = "semister_id" required>
                                <option value="">--select semister--</option>
                                  @foreach($semisters as $semister)
                                  <option value="{{$semister->id}}">{{$semister->short_name}}</option>
                                  @endforeach
                              </select>
                              </div>

                            <div class="col-sm-4">
                              <input type="file" class="form-control" name="studentlist" required/>
                            </div>
                            <div class="col-sm-4">
                              <button class="btn btn-primary" name="submit"  data-toggle="tooltip" data-placement="bottom" title="Upload Students"><i class="material-icons">arrow_upward</i></button>
                               <a class="btn btn-info" href="{{asset('formats/student_import.xlsx')}}"  data-toggle="tooltip" data-placement="bottom" title="Download File Format" download>
                                <i class="material-icons">arrow_downward</i>
                               </a>
                            </div>
                        </div>
                      </form>
                      </div>
                    </div>
                  </div>

                 <div class="panel panel-info">
                  <div class="panel-heading" role="tab" id="headingOne_2">
                    <h4 class="panel-title">
                      <a class="collapsed" role="button" data-toggle="collapse"  href="#collapseOne_2" aria-expanded="false" aria-controls="collapseOne_2"> Add Students using form
                      </a>
                    </h4>
                    </div>
                    <div id="collapseOne_2" class="panel-collapse collapse in" role="tabpanel"aria-labelledby="headingOne_2">
                      <div class="panel-body">
                          <form method="post" class="form-horizontal" action="{{ route('store-students') }}">
                             {{ csrf_field() }}

                          <div class="row clearfix">

                            <div class="col-sm-4">
                              <input type="hidden" name="acadmic_year_id" value="{{$acyear->id}}">
                              <select class="form-control" id="semister_id" name = "semister_id" onchange="myfun()" required>
                                <option value="">--select semister--</option>
                                  @foreach($semisters as $semister)
                                  <option value="{{$semister->id}}">{{$semister->short_name}}</option>
                                  @endforeach
                              </select>
                            </div>
                             <div class="col-sm-4">
                             <h4>Accadmic Year {{$acyear->from_year}} - {{$acyear->to_year}} </h4>
                            </div>

                             <div class="col-sm-12">

                  <div class="table-responsive">
                  <table id="dataTable" class="table dataTable">
                 <thead>
                      <th>Select</th>
                      <th>Roll No</th>
                      <th>Student Name</th>
                      <th>Batch</th>
                      <th>Elective Subject</th>
                 </thead>
                  <tbody>
                    <tr>
                    <p>

                    <td><input type="checkbox" id="md_checkbox_21" class="filled-in chk-col-red" checked required="required"/>
                    </td>

                    <td>
                     <input type="number"  class="form-control" placeholder="Roll No" name="roll_no[]">
                    </td>

                    <td>
                    <input type="text"  class="form-control"  placeholder="Student Name" name="student_name[]">
                    </td>
                    <td>
                      <select class="form-control" name="batch_id[]" required="true">
                        <option value="">--Select Batch--</option>
                        <option value="1">Batch I</option>
                        <option value="2">Batch II</option>
                        <option value="3">Batch III</option>
                        <option value="4">Batch IV</option>

                      </select>
                    </td>

                    <td>
                       <select class="form-control" id="elective_subject_id" name = "elective_subject_id[]" >
                                <option value="">--select elective subject--</option>
                      </select>
                    </td>
                   </p>
                    </tr>
                    </tbody>
                </table>
                <br>
                  <p>
                     <input type="submit" name="submit" value="Save" class="btn btn-success"  />
                      <input type="button" value="Add New Record" class="btn btn-primary"  onClick="addRow('dataTable')" />
                      <input type="button" value="Remove Record" class="btn btn-danger" onClick="deleteRow('dataTable')"  />
                  </p>
              </div>
              <div class="clear"></div>
              </div>
              </div>
            </form>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
</div>
</div>
</div>


 <script type="text/javascript">

  function myfun() {
    var semister_id =document.getElementById('semister_id').value;
    console.log(semister_id);

    $.ajax({
             type: 'post',
             url: '{{ route('select-elective-subject') }}',
            data:{
                    "semister_id":semister_id,
                 },
             async: true,
           dataType: 'json',
             success: function (data) {
              console.log(data);
                $('#elective_subject_id').children('option:not(:first)').remove();
                var html = '';
            for(var i = 0; i < data.length; i++){
console.log(data[i].id);
     var option=$('<option value='+data[i].id+'>'+data[i].name+'</option>');
  $('#elective_subject_id').append(option);

}
}
});
}

  function addRow(tableID) {
        var table = document.getElementById(tableID);
        var rowCount = table.rows.length;
        if(rowCount < 20){             // limit the user from creating fields more than your limits
            var row = table.insertRow(rowCount);
            var colCount = table.rows[0].cells.length;
            for(var i=0; i<colCount; i++) {
                var newcell = row.insertCell(i);
                newcell.innerHTML = table.rows[1].cells[i].innerHTML;
                }
          }else{
           alert("maximum 20 rows are allowded.");

      }
  }

function deleteRow(tableID) {
     var table = document.getElementById(tableID);
     var rowCount = table.rows.length;
     for(var i=0; i<rowCount; i++) {
     var row = table.rows[i];
     var chkbox = row.cells[0].childNodes[0];
      if(null != chkbox && true == chkbox.checked) {
      if(rowCount <= 2) {             // limit the user from removing all the fields
        alert("Cannot Remove all Rows.");
        break;
      }
      table.deleteRow(i);
      rowCount--;
      i--;
    }
  }
}
</script>

    </section>

@endsection

resources/views/students/students.blade.php
@extends('layouts.admin_layout')
@section('content')
  <section class="content">
   <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                         <div class="header">
                            <h2>Students List
                            </h2>
                        </div>
                        <div class="body">
                            @if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif
    @if (Session::has('error'))
          <div class="alert alert-danger">
        {{ session('error') }}
    </div>
    @endif
                                  <div class="panel panel-info">
                                            <div class="panel-heading" role="tab" id="headingOne_1">
                                                <h4 class="panel-title">
                                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion_1" href="#collapseOne_1" aria-expanded="false" aria-controls="collapseOne_1">
                                                       Click here to search student
                                                    </a>
                                                </h4>
                                            </div>
                                            <div id="collapseOne_1" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne_1">
                                                <div class="panel-body">
                                                   <form method="POST" action="{{ route('student-management-search') }}">
         {{ csrf_field() }}
         @component('layouts.search', ['title' => 'Search'])
          @component('layouts.two-cols-search-row', ['items' => ['Enter Student Name', 'Enter Year eg SE'],
          'oldVals' => [isset($searchingVals) ? $searchingVals['student_name'] : '', isset($searchingVals) ? $searchingVals['year'] : '']])
          @endcomponent
        @endcomponent
      </form>
                                                </div>
                                            </div>
                                        </div>


    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
      <div class="row">
        <div class="col-sm-12">

          <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
            <thead>
              <tr role="row">
                <th>Semister</th>
                <th>Roll No</th>
                <th>Student Name</th>
                <th>
                <a href="{{route('add-students')}}" class="btn bg-teal waves-effect" data-toggle="tooltip" data-placement="bottom" title="Add / import Students">
                <i class="material-icons">add</i>
                </a>
              </th>
              </tr>
            </thead>
            <tbody>
            @foreach ($students as $student)
                <tr>
                  <td>{{ $student->short_name }}</td>
                  <td>{{ $student->roll_no }}</td>
                  <td>{{ $student->student_name }}</td>
                  <td>
                     <a href = "{{ route('student-management.show',$student->id) }}" id="edit" class=" btn btn-warning btn-sm" data-toggle="tooltip" data-placement="bottom" title="Edit this Student">
               <i class="material-icons">edit</i>
</a>
            <button class="delete-modal btn btn-danger btn-sm" data-id="{{$student->id}}" data-student_name="{{$student->student_name}}" data-roll_no="{{$student->roll_no}}" data-toggle="tooltip" data-placement="bottom" title="Delete this Student">
               <i class="material-icons">delete</i>
            </button>
                  </td>
              </tr>
            @endforeach
            </tbody>
            <tfoot>
              <tr>
               <th>Year</th>
                <th>Roll No</th>
                <th>Student Name</th>
                <th>Action</th>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-5">
          <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to {{count($students)}} of {{count($students)}} entries</div>
        </div>
        <div class="col-sm-7">
          <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
            {{ $students->links() }}
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
        <form class="form-horizontal" role="modal">
          <div class="form-group">
            <label class="control-label col-sm-2" for="id">ID</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="id" disabled>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-2" for="Code">Code</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="code" name="code"
              placeholder="Faculty Unique Code" required>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-2" for="to_year">Name</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="short_name" name="short_name"
              placeholder="Faculty name" required>
            </div>
          </div>
        </form>

        {{-- Form Delete Post --}}
        <div class="deleteContent">
          Are You sure want to delete Roll no: <span class="code"></span> Student name  <span class="name"></span>?
          <span class="hidden id"></span>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn actionBtn" data-dismiss="modal" id="edit">
          <span id="footer_action_button" class="glyphicon"></span>
        </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal">
          <span class="glyphicon glyphicon"></span>close
        </button>
      </div>
    </div>
  </div>
</div>

<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>

<script type="text/javascript">
  $(document).on('click', '.edit-modal', function() {

    $('#footer_action_button').text("Update");
    $('#footer_action_button').addClass('glyphicon-check');
    $('#footer_action_button').removeClass('glyphicon-trash');
    $('.actionBtn').addClass('btn-success');
    $('.actionBtn').removeClass('btn-danger');
    $('.actionBtn').addClass('edit');
    $('.modal-title').text('Edit Faculty code');
    $('.deleteContent').hide();
    $('.form-horizontal').show();
    $('#id').val($(this).data('id'));

    $('#code').val($(this).data('code'));

    $('#short_name').val($(this).data('short_name'));

    $('#myModal').modal('show');

});



// form Delete function
    $(document).on('click', '.delete-modal', function() {
        $('#footer_action_button').text(" Delete");
        $('#footer_action_button').removeClass('glyphicon-check');
        $('#footer_action_button').addClass('glyphicon-trash');
        $('.actionBtn').removeClass('btn-success');
        $('.actionBtn').addClass('btn-danger');
        $('.actionBtn').addClass('delete');
        $('.modal-title').text('Delete Student');
        $('.id').text($(this).data('id'));
        $('.deleteContent').show();
        $('.form-horizontal').hide();
        $('.code').html($(this).data('roll_no'));
        $('.name').html($(this).data('student_name'));
        $('#myModal').modal('show');
    });

    $('.modal-footer').on('click', '.delete', function(){
      $.ajax({
        type: 'POST',
        url: 'student-management/deleteStudent',
        data: {
          '_token': $('input[name=_token]').val(),
          'id': $('.id').text()
        },
        success: function(data){
           $('.delete-modal').modal('hide');
           window.location = data.url;
        }
      });
    });


  function editStudent(obj) {
    var roll_no = obj.getAttribute('data-roll_no');
     var student_name = obj.getAttribute('data-student_name');
     console.log(roll_no,student_name);
        $.ajax({
             type: 'get',
             url: '{{ route('edit-student') }}',
            data:{
                    "roll_no":roll_no,
                     "student_name":student_name,
                 },
             async: true,
           dataType: 'json',
             success: function (data) {
              console.log($data);
             }
              });
  }
  function deleteStudent() {
    var test_id = $('#test_id').val();
     var subject_id = $('#subject_id').val();
     console.log(test_id,subject_id);
  }
</script>
    </section>

@endsection